### ISSUE TITLE
can't insert-to-middle-without-key

### ISSUE THREAD

**Issue by ghost** [dfilatov/vidom#25]
seems to be an issue with insert-to-middle-without-key in diff / patch algorithm. Everything else works just fine, except this one.

**Comment by dfilatov** [comment]
What do you mean? All tests including "insert-to-middle-without-key" passed.
Could you provide more details?

**Comment by dfilatov** [comment]
@marcorra ?

**Comment by marcorra** [comment]
I'm here. I was just occupied replying on the other posts and run checks. For this one. What browsers are you using? Processor and PC or MAC?  I ask because belive it or not it will work on a computer, but fails sometimes in Windows 8. For MAC, it will fail for older versions.

And I also ran this setup against jsDOM, and it fails. But in the native browser it works. Meaning this is not working server-side. Only client side.

**Comment by dfilatov** [comment]
vidom is tested in many browsers via saucelabs (you can see badge with browsers in readme). In these browsers all tests passed.
