### ISSUE TITLE
Performance tweaks and tips

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#51]
Some tricks to re-consider to gain better performance:

1. Re-factor your insertChild method. See how citoJS does it. You are only using 'insertBefore'.
   CitoJS are using replaceChild, insertBefore AND appendChild. All depends on where the node are located and the indexes.  'appendChild' are faster all over then 'insertBefore'.

2. Have a look at how cito does 'removeChild' and refactor your own. I't s also using nextSibling here.

3. make sure the addRootDomEventListerners only are set on the root node - document - as in REACT. So you NEVER set any addEventlisteners on the nodes itself. You use event delegation to bubble up and down to get an match. But not add listeners.

4. Avoid re-rendring of the same node, if it's already rendered

5. Get rid of prototype and the new keyword

**Comment by dfilatov** [comment]
1. only `insertBefore` is used within `insertChild` because `insertChild` is called only if there's next sibling. In other cases `appendChild` is called. So there's no sense to call anything except `insertBefore`.
2. Do you understand how `nextSibling` is used in cito.js and how it can be applied here? I don't.
3. The event delegation is already used.
4. There's no such case. A User isn't directly dealing with the rendering process.
5. I don't think it can bring valueable boost.

**Comment by rickardjanson** [comment]
@dfilatov Look what he did here: https://github.com/joelrich/citojs/commit/8b9c2734252f2dc77d76479e72379726fd7c8a27

You think you can do same solution, and also avoiding touching the DOM as mentioned in the comment?

A constructor are 35% slower then plain object. And the `new` keyword are terrible slow.

READ THIS: https://nemisj.com/js-without-new-and-this/

**Comment by rickardjanson** [comment]
http://yuiblog.com/blog/2006/11/13/javascript-we-hardly-new-ya/
